mkdir onnx_models
cd onnx_models
wget https://github.com/onnx/models/raw/master/vision/classification/alexnet/model/bvlcalexnet-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/caffenet/model/caffenet-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/densenet-121/model/densenet-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/efficientnet-lite4/model/efficientnet-lite4-11.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/inception_and_googlenet/googlenet/model/googlenet-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/inception_and_googlenet/inception_v2/model/inception-v2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/mobilenet/model/mobilenetv2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/rcnn_ilsvrc13/model/rcnn-ilsvrc13-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet101-v1-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet101-v2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet152-v1-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet152-v2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet18-v1-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet18-v2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet34-v1-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet34-v2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet50-caffe2-v1-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet50-v1-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/resnet/model/resnet50-v2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/shufflenet/model/shufflenet-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/squeezenet/model/squeezenet1.0-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/vgg/model/vgg16-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/vgg/model/vgg16-bn-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/vgg/model/vgg19-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/vgg/model/vgg19-bn-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/vgg/model/vgg19-caffe2-7.onnx
wget https://github.com/onnx/models/raw/master/vision/classification/zfnet-512/model/zfnet512-7.onnx